apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ocpvirt-workloads-ha-argocd
rules:
  - apiGroups:
      - self-node-remediation.medik8s.io
    resources:
      - selfnoderemediationtemplates
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - remediation.medik8s.io
    resources:
      - nodehealthchecks
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - fence-agents-remediation.medik8s.io
    resources:
      - fenceagentsremediationtemplates
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - machine-deletion-remediation.medik8s.io
    resources:
      - machinedeletionremediationtemplates
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - operator.openshift.io
    resources:
      - kubedeschedulers
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ocpvirt-workloads-ha-argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ocpvirt-workloads-ha-argocd
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
