apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/openshift-workload-availability
  - ../../../node-maintenance-operator/install
  - ../../../self-node-remediation-operator/install
  - ../../../node-health-check-operator/install
  - ../../../kube-descheduler-operator/install
