apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/base-openshift-workload-availability
  - ../../components/node-maintenance-operator/install
  - ../../components/self-node-remediation-operator/install
  - ../../components/node-health-check-operator/install
  - ../../components/kube-descheduler-operator/install
