apiVersion: operator.openshift.io/v1
kind: KubeDescheduler
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "8"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  managementState: Managed
  profileCustomizations:
    devLowNodeUtilizationThresholds: Medium
  profiles:
  - LifecycleAndUtilization
