apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/openshift-workload-availability
  - ../../node-maintenance-operator
  - ../../self-node-remediation-operator
  - ../../node-health-check-operator
  - ../../kube-descheduler-operator
