apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocpvirt-workloads-ha-install
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:ravishar-rh/operator-config-files.git
    targetRevision: main
    path: modules/ocpvirt-workloads-ha/overlays/install
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
    - group: operators.coreos.com
      kind: Subscription
      jqPathExpressions:
        - .status
        - .spec.startingCSV
    - group: operators.coreos.com
      kind: InstallPlan
      jqPathExpressions:
        - .spec.approved
        - .status
