apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocpvirt-workloads-ha-config
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:ravishar-rh/operator-config-files.git
    targetRevision: main
    path: modules/ocpvirt-workloads-ha/overlays/config
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-workload-availability
  dependsOn:
    - name: ocpvirt-workloads-ha-install
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: -1
      backoff:
        duration: 1m
        factor: 2
        maxDuration: 10m
