apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocpvirt-workloads-ha-rbac
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:ravishar-rh/operator-config-files.git
    targetRevision: main
    path: modules/ocpvirt-workloads-ha/argocd/rbac
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
