apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocpvirt-workloads-ha-root
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:ravishar-rh/operator-config-files.git
    targetRevision: main
    path: modules/ocpvirt-workloads-ha/argocd/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
